FROM node:lts-slim AS builder

WORKDIR /app

COPY . .
# In conjunction with the .dockerignore file
# This will only copy the files that we want
# And node_modules, build, log, etc will be ignored
RUN npm ci

ENTRYPOINT sls deploy
