DROP TABLE IF EXISTS note_associate CASCADE;
DROP TABLE IF EXISTS user_batch CASCADE;
DROP TABLE IF EXISTS associates CASCADE;
DROP TABLE IF EXISTS note CASCADE;
DROP TABLE IF EXISTS batch CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS ROLE CASCADE;
DROP TYPE IF EXISTS SCORE CASCADE;