DROP TABLE IF EXISTS note_associate;
DROP TABLE IF EXISTS user_batch;
DROP TABLE IF EXISTS associate;
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS batch;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS ROLE;
DROP TYPE IF EXISTS SCORE;